import { createContext, useContext, useState } from 'react';

const strings = {
  nl: {
    brandSub: 'Video Production Studio',
    navStudio: 'Studio',
    navBeheer: 'Beheer',
    navEditors: 'Editors',
    team: 'Team',
    logout: 'Uitloggen',
    logoutConfirmTitle: 'Uitloggen?',
    logoutConfirmBody: 'Weet je zeker dat je wilt uitloggen?',
    home: 'Home', agenda: 'Agenda', klanten: 'Klanten', taken: 'Taken',
    archief: 'Archief', workspace: 'Workspace', checker: 'Video Checker', pulse: 'Studio Pulse',
    activeClients: 'Actieve klanten', openTasks: 'Open taken',
    shootsMonth: 'Shoots deze maand', urgent: 'Urgent',
    kpiTasksInProgress: 'Taken in uitvoering',
    kpiUrgentClients: 'Urgente klanten',
    kpiDescOngoingProjects: 'Lopende trajecten',
    kpiDescScheduled: 'Gepland in agenda',
    kpiDescAcrossProjects: 'Over alle projecten',
    kpiDescRequiresAttention: 'Vereist aandacht',
    dayModalNoEvents: 'Geen events op deze dag.',
    addEventToDay: '+ Event toevoegen',
    eventFormTitle: 'Nieuw event toevoegen',
    eventFormTitleEdit: 'Event bewerken',
    eventDateTimeLabel: 'Datum en tijd',
    eventAssigneeLabel: 'Toegewezen aan',
    eventAssigneePlaceholder: '— Kies teamlid —',
    eventNameLabel: 'Naam',
    eventNamePlaceholder: 'Event naam…',
    eventDateLabel: 'Datum',
    eventClientLabel: 'Klant',
    eventClientPlaceholder: '— Kies klant —',
    eventNotesPlaceholder: 'Optioneel…',
    thisWeek: 'Deze week', nextWeek: 'Volgende week',
    homeStudioSubtitle: 'Studio overzicht · 4REEL Productions',
    activity: 'Activiteit', contact: 'Contactpersoon',
    phone: 'Telefoon', clientSince: 'Klant sinds',
    phase: 'Fase', statusLabel: 'Status',
    urgentStatus: 'Urgent', active: 'Actief', notes: 'Notities',
    todo: 'Te doen', bezig: 'Bezig', review: 'Review', klaar: 'Klaar',
    filter: 'Filter:', allTasks: 'Alle',
    tasksKanbanSubtitle: 'Projecttaken over alle klanten',
    addTask: '+ Taak', addEvent: '+ Nieuw event',
    save: 'Opslaan', cancel: 'Annuleren', close: 'Sluiten',
    delete: 'Verwijderen', restore: '↩ Herstellen',
    archive: '→ Archiveren',
    wsFilmsLabel: 'Filmpjes', wsFilmsReady: "klaar",
    wsVidColName: 'Bestandsnaam', wsVidColFase: 'Edit Fase',
    wsVidColAssets: 'Assets Drive', wsVidColExport: 'Export Frame.io',
    wsVidColNotes: 'Notities', wsAddDrivePH: '+ Drive link toevoegen',
    wsAddExportPH: '+ Frame.io link', wsVidNamePrompt: 'Naam van het filmpje:',
    wsAddWorkspace: '+ Workspace toevoegen',
    wsAddWorkspaceFooter: '+ Workspace aanmaken',
    shotlistAdd: '+ Shot', reset: '↺ Reset alle vinkjes',
    shootMode: '⛶ Shoot-modus', exitShootMode: '✕ Shoot-modus',
    script: 'Script', brandAssets: 'Brand Assets', shotlist: 'Shotlist', sop: 'SOP',
    stuurNaarKlant: '→ Stuur naar klant', bijKlant: '👁 Bij klant', klantAkkoord: '✓ Klant akkoord',

    loginWrongRoleTeam: 'Dit account is geen teamaccount. Gebruik een teamaccount in Team-modus.',
    loginWrongRoleClient: 'Dit account is geen klantaccount. Gebruik een klantaccount in Klant-modus.',
    loginInvalid: 'Ongeldig e-mailadres of wachtwoord.',
    loginSuccess: 'Succesvol ingelogd. Je wordt doorgestuurd…',
    loginNetworkError: 'Geen verbinding met de server. Controleer je internet of probeer later opnieuw.',
    loginValEmailRequired: 'Vul je e-mailadres in.',
    loginValEmailInvalid: 'Vul een geldig e-mailadres in.',
    loginValPasswordRequired: 'Vul je wachtwoord in.',
    loginValPasswordSpaces: 'Wachtwoord mag niet alleen spaties zijn.',
    loginValServerForm: 'E-mail en wachtwoord zijn verplicht en het e-mailadres moet geldig zijn.',
    forgotPasswordLink: 'Wachtwoord vergeten?',
    forgotTitle: 'Wachtwoord herstellen',
    forgotSub:
      'Vul het e-mailadres van je klantportaal in. Als dit adres bij een account hoort, sturen we je een link om je wachtwoord te herstellen.',
    forgotSubmit: 'Link versturen',
    forgotSubmitLoading: 'Bezig…',
    forgotBack: '← Terug naar inloggen',
    forgotSuccess:
      'Als dit e-mailadres bij een portaalaccount hoort, ontvang je een herstelmail. Controleer ook je spam.',
    resetCheckingLink: 'Link controleren…',
    resetTitle: 'Nieuw wachtwoord',
    resetSub: 'Kies een nieuw wachtwoord voor je klantportaal.',
    resetNewPasswordLabel: 'Nieuw wachtwoord',
    resetConfirmPasswordLabel: 'Bevestig wachtwoord',
    resetSubmit: 'Wachtwoord opslaan',
    resetSubmitLoading: 'Opslaan…',
    resetBackToLogin: '← Terug naar inloggen',
    resetSuccess: 'Je wachtwoord is bijgewerkt. Je kunt nu inloggen.',
    resetInvalidTitle: 'Ongeldige link',
    resetInvalidLink: 'Deze herstellink is ongeldig of verlopen. Vraag een nieuwe link aan.',
    resetValPasswordMismatch: 'Wachtwoorden komen niet overeen.',
    resetValConfirmRequired: 'Bevestig je wachtwoord.',
    portalTitleClient: 'Klantportaal',
    portalTitleTeam: '4REEL Team',
    portalSubClient: 'Log in met je accountgegevens',
    portalSubTeam: 'Log in met je teamaccount',
    portalTabClient: '👤 Klant',
    portalTabTeam: '🔐 4REEL Team',
    portalEmailLabel: 'Emailadres',
    portalPasswordLabel: 'Wachtwoord',
    portalEmailPlaceholder: 'jouw@email.nl',
    portalLoginSubmit: 'Inloggen →',
    portalLoginSubmitLoading: 'Inloggen…',
    portalPoweredBy: 'Beveiligd portaal · 4REEL Productions',
    portalLoginTypeAria: 'Inlogtype',
    portalTeamLoggedTitle: 'Ingelogd als teamlid',
    portalTeamLoggedBody: 'Gebruik het dashboard voor teamtoegang.',
    portalTeamLoggedLink: '→ Ga naar dashboard',
    eventCreateForbidden: 'Alleen team mag events aanmaken.',
    eventValidationNameRequired: 'Vul een eventnaam in.',
    eventValidationDateRequired: 'Kies een datum.',
    eventValidationDateTimeRequired: 'Kies datum en tijd.',
    eventValidationAssigneeRequired: 'Wijs het event toe aan een teamlid.',
    eventValidationClientRequired: 'Selecteer een klant.',
    eventSaveFailed: 'Event kon niet worden opgeslagen.',
    addTeamMember: 'Teamlid toevoegen',
    addTeamMemberTitle: 'Nieuw teamlid',
    teamEmailLabel: 'E-mail',
    teamPasswordLabel: 'Wachtwoord',
    teamNameLabel: 'Naam',
    teamRoleLabel: 'Rol',
    teamInitialsLabel: 'Initialen',
    teamColorLabel: 'Kleur',
    teamLoadError: 'Team kon niet worden geladen.',
    teamCreateError: 'Teamlid kon niet worden aangemaakt.',
    teamPasswordHint: 'Minimaal 8 tekens',
    teamLoading: 'Laden…',
    teamValEmailRequired: 'E-mail is verplicht.',
    teamValEmailInvalid: 'Vul een geldig e-mailadres in.',
    teamValEmailTaken: 'Dit e-mailadres is al in gebruik.',
    teamValPasswordRequired: 'Wachtwoord is verplicht.',
    teamValPasswordLength: 'Wachtwoord moet minimaal 8 tekens zijn.',
    teamValNameRequired: 'Naam is verplicht.',
    teamValRoleRequired: 'Rol is verplicht.',
    taskFormTitle: 'Nieuwe taak aanmaken',
    taskTitleLabel: 'Titel',
    taskTitlePlaceholder: 'Taaknaam…',
    taskAssigneeLabel: 'Toegewezen aan',
    taskAssigneePlaceholder: '— Kies teamlid —',
    taskAssigneeEmpty: 'Geen teamleden',
    taskPriorityLabel: 'Prioriteit',
    taskDeadlineLabel: 'Deadline',
    taskClientLabel: 'Klant',
    taskClientPlaceholder: '— Kies klant —',
    taskCreateSubmit: 'Taak aanmaken',
    taskArchivedToast: 'Taak gearchiveerd',
    taskPriorityHigh: 'Hoog',
    taskPriorityNormal: 'Normaal',
    taskPriorityLow: 'Laag',
    taskValTitleRequired: 'Vul een titel in.',
    taskValTitleMax: 'Titel mag maximaal 200 tekens zijn.',
    taskValAssigneeRequired: 'Toegewezen aan is verplicht.',
    taskValAssigneeNoTeam: 'Er zijn geen teamleden om toe te wijzen.',
    taskValAssigneeInvalid: 'Kies een geldig teamlid.',
    taskValPriorityInvalid: 'Kies een geldige prioriteit.',
    taskValDueRequired: 'Kies een deadline.',
    taskValDueInvalid: 'Kies een geldige datum.',
    taskValClientRequired: 'Selecteer een klant.',
    taskValClientInvalid: 'Kies een geldige klant uit de lijst.',

    archivePageTitle: 'Archief',
    archivePageTitleEm: '— Afgeronde taken',
    archiveArchivedTasksSuffix: 'gearchiveerde taken',
    archiveAllTasks: 'Alle taken',
    archiveSearchPlaceholder: 'Zoeken…',
    archiveMonth: 'Maand',
    archiveAllMonths: 'Alle maanden',
    archivePerson: 'Persoon',
    archiveEveryone: 'Iedereen',
    archiveFilterReason: 'Status',
    archiveAll: 'Alles',
    archiveReasonDelivered: 'Opgeleverd',
    archiveReasonCompleted: 'Afgerond',
    archiveReasonManual: 'Handmatig',
    archiveSort: 'Sorteren',
    archiveSortNewest: 'Nieuwste eerst',
    archiveSortOldest: 'Oudste eerst',
    archiveSortAZ: 'A → Z',
    archiveSortZA: 'Z → A',
    archiveReset: '↺ Reset',
    archiveClientFallback: 'Client',
    archiveActiveFilterSingular: '1 actieve filter',
    archiveActiveFilterPlural: '{n} actieve filters',
    archiveOf: 'van',
    archiveTaskWord: 'taken',
    archiveEmpty: 'Geen taken gevonden met de huidige filters.',
    archiveClearFilters: '↺ Filters wissen',
    archiveModalAssignee: 'Toegewezen',
    archiveModalArchived: 'Gearchiveerd',
    archiveModalReason: 'Reden',
    archiveModalDescription: 'Beschrijving',
    archiveModalChecklist: 'Checklist',
    archiveRestoreToTodo: '↩ Herstellen naar To Do',
    taskRestoredToast: 'Taak hersteld',

    pulseTeamOnly: 'Studio Pulse is alleen beschikbaar voor het team.',
    pulseLoadError: 'Kon Studio Pulse niet laden.',
    pulsePageTitle: 'Studio Pulse',
    pulsePageTitleEm: '— Bedrijfsgezondheid',
    pulseSubtitle: 'Live inzicht in workload, pipeline en groei',
    pulseRefresh: 'Vernieuwen',
    pulseKpiBatchesActive: 'Batches actief',
    pulseKpiClientsSubOne: '{n} klant',
    pulseKpiClientsSubMany: '{n} klanten',
    pulseKpiVideosPipeline: 'Videos in pipeline',
    pulseKpiNotStartedSub: '{n} nog te starten',
    pulseKpiShootsPlanned: 'Shoots gepland',
    pulseKpiThisMonthSub: '{n} deze maand',
    pulseKpiDeliveredEver: 'Opgeleverd ooit',
    pulseKpiDeliveredSubMonth: '{delivered} deze maand',
    pulseKpiDeliveredSubTasksSuffix: ' · {openTasks} open taken',
    pulseStageNotStarted: 'Nog te starten',
    pulseStageInEdit: 'In bewerking',
    pulseStageInReview: 'In review',
    pulseStageDelivered: 'Opgeleverd',
    pulseCardPipeline: 'Video Pipeline',
    pulseTeamCapacity: 'Team Capaciteit',
    pulseTeamEmpty:
      'Nog geen teamleden of editors gekoppeld. Voeg teamleden toe of wijs een editor toe bij een batch.',
    pulseTeamLoadTooltip: 'Videos in actieve fases',
    pulseCapacityAlmostFull: 'Bijna vol',
    pulseCapacityGood: 'Goed bezet',
    pulseCapacityRoom: 'Ruimte beschikbaar',
    pulseCapacityHealthy: 'Gezond',
    pulseCardReminders: '🔔 Slimme reminders',
    pulseAlertDeadlineToday: 'Deadline VANDAAG: {name}',
    pulseAlertDeadlineOneDay: 'Deadline over 1 dag: {name}',
    pulseAlertDeadlineDays: 'Deadline over {days} dagen: {name}',
    pulseAlertDeadlineVideosOne: '{open} video nog niet klaar voor {client}',
    pulseAlertDeadlineVideosMany: '{open} videos nog niet klaar voor {client}',
    pulseThisClient: 'deze klant',
    pulseAlertDeadlineAction: 'Ga naar Workspace → {target}',
    pulseAlertLowWorkloadTitle: 'Lage workload — ruimte voor nieuwe klanten',
    pulseAlertLowWorkloadDesc: 'Team zit op {pct}% capaciteit. Goed moment voor acquisitie.',
    pulseAlertLowWorkloadAction: 'Overweeg {n} nieuwe projecten aan te nemen',
    pulseAlertHighWorkloadTitle: 'Team bijna vol — {pct}% bezet',
    pulseAlertHighWorkloadDesc: 'Wees voorzichtig met het aannemen van nieuwe opdrachten.',
    pulseAlertHighWorkloadAction: 'Bespreek capaciteitsplanning met het team',
    pulseAlertReviewTitle: '{n} videos wachten op review/feedback',
    pulseAlertReviewDesc: 'Follow-up bij klanten versnelt de pipeline.',
    pulseAlertReviewAction: 'Controleer: Workspace → Export links verzonden?',
    pulseAlertShootsLowTitle: 'Weinig shoots ingepland ({n})',
    pulseAlertShootsLowDesc: 'Minder dan 2 shoots gepland voor de komende periode.',
    pulseAlertShootsLowAction: 'Plan nieuwe shootdagen in via de Agenda',
    pulseAlertIdleClientsOne: '1 klant zonder actieve videos',
    pulseAlertIdleClientsMany: '{n} klanten zonder actieve videos',
    pulseAlertIdleClientsAction: 'Stuur een check-in of plan nieuwe shoot in',
    pulseAlertAllGoodTitle: 'Alles ziet er goed uit!',
    pulseAlertAllGoodDesc: 'Geen urgente aandachtspunten gevonden. Goed bezig!',
    pulseCardGrowth: '📈 Groei — opgeleverde projecten',
    pulseGrowthEmpty: 'Nog geen maandoverzicht beschikbaar.',
    pulseGrowthFootnote: 'Laatste 6 maanden · gearchiveerde taken + opgeleverde workspace videos',
    pulseCardClientHealth: '🏢 Klantgezondheid',
    pulseClientsEmpty: 'Nog geen klanten — voeg klanten toe onder Klanten.',
    pulseClientBatchOne: 'batch',
    pulseClientBatchMany: 'batches',
    pulseClientVideoOne: 'video',
    pulseClientVideoMany: 'videos',
    pulseClientUrgent: 'Urgent',
    pulseBannerTitle: 'Capaciteitsruimte beschikbaar',
    pulseBannerBody:
      'Het team kan nog ca. {n} nieuwe projecten aan. Nu is het moment voor acquisitie.',
    pulseBannerCta: '→ Naar klanten',
  },
  en: {
    brandSub: 'Video Production Studio',
    navStudio: 'Studio',
    navBeheer: 'Operations',
    navEditors: 'Editors',
    team: 'Team',
    logout: 'Log out',
    logoutConfirmTitle: 'Log out?',
    logoutConfirmBody: 'Are you sure you want to log out?',
    home: 'Home', agenda: 'Agenda', klanten: 'Clients', taken: 'Tasks',
    archief: 'Archive', workspace: 'Workspace', checker: 'Video Checker', pulse: 'Studio Pulse',
    activeClients: 'Active clients', openTasks: 'Open tasks',
    shootsMonth: 'Shoots this month', urgent: 'Urgent',
    kpiTasksInProgress: 'Tasks in progress',
    kpiUrgentClients: 'Urgent clients',
    kpiDescOngoingProjects: 'Ongoing projects',
    kpiDescScheduled: 'Scheduled',
    kpiDescAcrossProjects: 'Across all projects',
    kpiDescRequiresAttention: 'Requires attention',
    dayModalNoEvents: 'No events on this day.',
    addEventToDay: '+ Add event',
    eventFormTitle: 'Add new event',
    eventFormTitleEdit: 'Edit event',
    eventDateTimeLabel: 'Date and time',
    eventAssigneeLabel: 'Assigned to',
    eventAssigneePlaceholder: '— Select team member —',
    eventNameLabel: 'Name',
    eventNamePlaceholder: 'Event name…',
    eventDateLabel: 'Date',
    eventClientLabel: 'Client',
    eventClientPlaceholder: '— Select client —',
    eventNotesPlaceholder: 'Optional…',
    thisWeek: 'This week', nextWeek: 'Next week',
    homeStudioSubtitle: 'Studio overview · 4REEL Productions',
    activity: 'Activity', contact: 'Contact person',
    phone: 'Phone', clientSince: 'Client since',
    phase: 'Phase', statusLabel: 'Status',
    urgentStatus: 'Urgent', active: 'Active', notes: 'Notes',
    todo: 'To do', bezig: 'In progress', review: 'Review', klaar: 'Done',
    filter: 'Filter:', allTasks: 'All',
    tasksKanbanSubtitle: 'Project tasks across all clients',
    addTask: '+ Task', addEvent: '+ New event',
    save: 'Save', cancel: 'Cancel', close: 'Close',
    delete: 'Delete', restore: '↩ Restore',
    archive: '→ Archive',
    wsFilmsLabel: 'Videos', wsFilmsReady: 'ready',
    wsVidColName: 'Filename', wsVidColFase: 'Edit Phase',
    wsVidColAssets: 'Assets Drive', wsVidColExport: 'Export Frame.io',
    wsVidColNotes: 'Notes', wsAddDrivePH: '+ Add Drive link',
    wsAddExportPH: '+ Frame.io link', wsVidNamePrompt: 'Video filename:',
    wsAddWorkspace: '+ Add Workspace',
    wsAddWorkspaceFooter: '+ Create workspace',
    shotlistAdd: '+ Shot', reset: '↺ Reset all checks',
    shootMode: '⛶ Shoot mode', exitShootMode: '✕ Shoot mode',
    script: 'Script', brandAssets: 'Brand Assets', shotlist: 'Shotlist', sop: 'SOP',
    stuurNaarKlant: '→ Send to client', bijKlant: '👁 At client', klantAkkoord: '✓ Client approved',

    loginWrongRoleTeam: 'This account is not a team account. Use a team account in Team mode.',
    loginWrongRoleClient: 'This account is not a client account. Use a client account in Client mode.',
    loginInvalid: 'Invalid email or password.',
    loginSuccess: 'Signed in successfully. Redirecting…',
    loginNetworkError: 'Could not reach the server. Check your connection or try again later.',
    loginValEmailRequired: 'Enter your email address.',
    loginValEmailInvalid: 'Enter a valid email address.',
    loginValPasswordRequired: 'Enter your password.',
    loginValPasswordSpaces: 'Password cannot be only spaces.',
    loginValServerForm: 'Email and password are required and the email must be valid.',
    forgotPasswordLink: 'Forgot password?',
    forgotTitle: 'Reset password',
    forgotSub:
      'Enter the email address you use for the client portal. If it matches an account, we will send a link to reset your password.',
    forgotSubmit: 'Send reset link',
    forgotSubmitLoading: 'Please wait…',
    forgotBack: '← Back to sign in',
    forgotSuccess:
      'If this email is linked to a portal account, you will receive a reset email. Check your spam folder too.',
    resetCheckingLink: 'Checking your link…',
    resetTitle: 'New password',
    resetSub: 'Choose a new password for your client portal.',
    resetNewPasswordLabel: 'New password',
    resetConfirmPasswordLabel: 'Confirm password',
    resetSubmit: 'Save password',
    resetSubmitLoading: 'Saving…',
    resetBackToLogin: '← Back to sign in',
    resetSuccess: 'Your password has been updated. You can sign in now.',
    resetInvalidTitle: 'Invalid link',
    resetInvalidLink: 'This reset link is invalid or has expired. Request a new one.',
    resetValPasswordMismatch: 'Passwords do not match.',
    resetValConfirmRequired: 'Please confirm your password.',
    portalTitleClient: 'Client portal',
    portalTitleTeam: '4REEL Team',
    portalSubClient: 'Sign in with your account details',
    portalSubTeam: 'Sign in with your team account',
    portalTabClient: '👤 Client',
    portalTabTeam: '🔐 4REEL Team',
    portalEmailLabel: 'Email',
    portalPasswordLabel: 'Password',
    portalEmailPlaceholder: 'you@email.com',
    portalLoginSubmit: 'Sign in →',
    portalLoginSubmitLoading: 'Signing in…',
    portalPoweredBy: 'Secure portal · 4REEL Productions',
    portalLoginTypeAria: 'Sign-in type',
    portalTeamLoggedTitle: 'Signed in as team member',
    portalTeamLoggedBody: 'Use the dashboard for team access.',
    portalTeamLoggedLink: '→ Go to dashboard',
    eventCreateForbidden: 'Only team members can create events.',
    eventValidationNameRequired: 'Enter an event name.',
    eventValidationDateRequired: 'Choose a date.',
    eventValidationDateTimeRequired: 'Choose date and time.',
    eventValidationAssigneeRequired: 'Assign the event to a team member.',
    eventValidationClientRequired: 'Select a client.',
    eventSaveFailed: 'Could not save the event.',
    addTeamMember: 'Add member',
    addTeamMemberTitle: 'New team member',
    teamEmailLabel: 'Email',
    teamPasswordLabel: 'Password',
    teamNameLabel: 'Name',
    teamRoleLabel: 'Role',
    teamInitialsLabel: 'Initials',
    teamColorLabel: 'Color',
    teamLoadError: 'Could not load the team.',
    teamCreateError: 'Could not create the team member.',
    teamPasswordHint: 'At least 8 characters',
    teamLoading: 'Loading…',
    teamValEmailRequired: 'Email is required.',
    teamValEmailInvalid: 'Enter a valid email address.',
    teamValEmailTaken: 'That email address is already in use.',
    teamValPasswordRequired: 'Password is required.',
    teamValPasswordLength: 'Password must be at least 8 characters.',
    teamValNameRequired: 'Name is required.',
    teamValRoleRequired: 'Role is required.',
    taskFormTitle: 'Create new task',
    taskTitleLabel: 'Title',
    taskTitlePlaceholder: 'Task name…',
    taskAssigneeLabel: 'Assigned to',
    taskAssigneePlaceholder: '— Select team member —',
    taskAssigneeEmpty: 'No team members',
    taskPriorityLabel: 'Priority',
    taskDeadlineLabel: 'Due date',
    taskClientLabel: 'Client',
    taskClientPlaceholder: '— Select client —',
    taskCreateSubmit: 'Create task',
    taskArchivedToast: 'Task archived',
    taskPriorityHigh: 'High',
    taskPriorityNormal: 'Normal',
    taskPriorityLow: 'Low',
    taskValTitleRequired: 'Enter a title.',
    taskValTitleMax: 'Title must be at most 200 characters.',
    taskValAssigneeRequired: 'Assigned to is required.',
    taskValAssigneeNoTeam: 'There are no team members to assign.',
    taskValAssigneeInvalid: 'Choose a valid team member.',
    taskValPriorityInvalid: 'Choose a valid priority.',
    taskValDueRequired: 'Choose a due date.',
    taskValDueInvalid: 'Choose a valid date.',
    taskValClientRequired: 'Select a client.',
    taskValClientInvalid: 'Choose a valid client from the list.',

    archivePageTitle: 'Archive',
    archivePageTitleEm: '— Completed tasks',
    archiveArchivedTasksSuffix: 'archived tasks',
    archiveAllTasks: 'All tasks',
    archiveSearchPlaceholder: 'Search…',
    archiveMonth: 'Month',
    archiveAllMonths: 'All months',
    archivePerson: 'Person',
    archiveEveryone: 'Everyone',
    archiveFilterReason: 'Reason',
    archiveAll: 'All',
    archiveReasonDelivered: 'Delivered',
    archiveReasonCompleted: 'Completed',
    archiveReasonManual: 'Manual',
    archiveSort: 'Sort',
    archiveSortNewest: 'Newest first',
    archiveSortOldest: 'Oldest first',
    archiveSortAZ: 'A → Z',
    archiveSortZA: 'Z → A',
    archiveReset: '↺ Reset',
    archiveClientFallback: 'Client',
    archiveActiveFilterSingular: '1 active filter',
    archiveActiveFilterPlural: '{n} active filters',
    archiveOf: 'of',
    archiveTaskWord: 'tasks',
    archiveEmpty: 'No tasks match the current filters.',
    archiveClearFilters: '↺ Clear filters',
    archiveModalAssignee: 'Assigned',
    archiveModalArchived: 'Archived',
    archiveModalReason: 'Reason',
    archiveModalDescription: 'Description',
    archiveModalChecklist: 'Checklist',
    archiveRestoreToTodo: '↩ Restore to To do',
    taskRestoredToast: 'Task restored',

    pulseTeamOnly: 'Studio Pulse is only available to the team.',
    pulseLoadError: 'Could not load Studio Pulse.',
    pulsePageTitle: 'Studio Pulse',
    pulsePageTitleEm: '— Business health',
    pulseSubtitle: 'Live view of workload, pipeline and growth',
    pulseRefresh: 'Refresh',
    pulseKpiBatchesActive: 'Active batches',
    pulseKpiClientsSubOne: '{n} client',
    pulseKpiClientsSubMany: '{n} clients',
    pulseKpiVideosPipeline: 'Videos in pipeline',
    pulseKpiNotStartedSub: '{n} not yet started',
    pulseKpiShootsPlanned: 'Shoots scheduled',
    pulseKpiThisMonthSub: '{n} this month',
    pulseKpiDeliveredEver: 'Delivered (all time)',
    pulseKpiDeliveredSubMonth: '{delivered} this month',
    pulseKpiDeliveredSubTasksSuffix: ' · {openTasks} open tasks',
    pulseStageNotStarted: 'Not started',
    pulseStageInEdit: 'In edit',
    pulseStageInReview: 'In review',
    pulseStageDelivered: 'Delivered',
    pulseCardPipeline: 'Video pipeline',
    pulseTeamCapacity: 'Team capacity',
    pulseTeamEmpty:
      'No team members or editors linked yet. Add team members or assign an editor on a batch.',
    pulseTeamLoadTooltip: 'Videos in active stages',
    pulseCapacityAlmostFull: 'Almost full',
    pulseCapacityGood: 'Well utilised',
    pulseCapacityRoom: 'Capacity available',
    pulseCapacityHealthy: 'Healthy',
    pulseCardReminders: '🔔 Smart reminders',
    pulseAlertDeadlineToday: 'Deadline TODAY: {name}',
    pulseAlertDeadlineOneDay: 'Deadline in 1 day: {name}',
    pulseAlertDeadlineDays: 'Deadline in {days} days: {name}',
    pulseAlertDeadlineVideosOne: '{open} video not yet done for {client}',
    pulseAlertDeadlineVideosMany: '{open} videos not yet done for {client}',
    pulseThisClient: 'this client',
    pulseAlertDeadlineAction: 'Go to Workspace → {target}',
    pulseAlertLowWorkloadTitle: 'Low workload — room for new clients',
    pulseAlertLowWorkloadDesc: 'The team is at {pct}% capacity. A good moment for new business.',
    pulseAlertLowWorkloadAction: 'Consider taking on {n} new projects',
    pulseAlertHighWorkloadTitle: 'Team nearly at capacity — {pct}% utilised',
    pulseAlertHighWorkloadDesc: 'Be careful about taking on new assignments.',
    pulseAlertHighWorkloadAction: 'Discuss capacity planning with the team',
    pulseAlertReviewTitle: '{n} videos waiting for review/feedback',
    pulseAlertReviewDesc: 'Following up with clients speeds up the pipeline.',
    pulseAlertReviewAction: 'Check: Workspace → export links sent?',
    pulseAlertShootsLowTitle: 'Few shoots scheduled ({n})',
    pulseAlertShootsLowDesc: 'Fewer than 2 shoots planned for the coming period.',
    pulseAlertShootsLowAction: 'Schedule new shoot days in the Agenda',
    pulseAlertIdleClientsOne: '1 client with no active videos',
    pulseAlertIdleClientsMany: '{n} clients with no active videos',
    pulseAlertIdleClientsAction: 'Send a check-in or schedule a new shoot',
    pulseAlertAllGoodTitle: 'Everything looks good!',
    pulseAlertAllGoodDesc: 'No urgent attention items. Keep it up!',
    pulseCardGrowth: '📈 Growth — delivered projects',
    pulseGrowthEmpty: 'No monthly overview available yet.',
    pulseGrowthFootnote: 'Last 6 months · archived tasks + delivered workspace videos',
    pulseCardClientHealth: '🏢 Client health',
    pulseClientsEmpty: 'No clients yet — add clients under Clients.',
    pulseClientBatchOne: 'batch',
    pulseClientBatchMany: 'batches',
    pulseClientVideoOne: 'video',
    pulseClientVideoMany: 'videos',
    pulseClientUrgent: 'Urgent',
    pulseBannerTitle: 'Capacity available',
    pulseBannerBody:
      'The team can still take on about {n} new projects. A good moment for new business.',
    pulseBannerCta: '→ Go to clients',
  }
};

const LangContext = createContext(null);

export function LangProvider({ children }) {
  const [lang, setLang] = useState('nl');
  const t = (key, vars) => {
    let s = strings[lang][key];
    if (s == null) return key;
    if (vars && typeof vars === 'object') {
      for (const [k, v] of Object.entries(vars)) {
        s = s.split(`{${k}}`).join(String(v));
      }
    }
    return s;
  };
  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  );
}

export const useLang = () => useContext(LangContext);
