import { createContext, useContext, useState } from 'react';

const strings = {
  nl: {
    brandSub: 'Video Production Studio',
    navStudio: 'Studio',
    navBeheer: 'Beheer',
    navEditors: 'Editors',
    team: 'Team',
    logout: 'Uitloggen',
    logoutConfirmTitle: 'Uitloggen?',
    logoutConfirmBody: 'Weet je zeker dat je wilt uitloggen?',
    home: 'Home', agenda: 'Agenda', klanten: 'Klanten', taken: 'Taken',
    archief: 'Archief', workspace: 'Workspace', pulse: 'Studio Pulse',
    activeClients: 'Actieve klanten', openTasks: 'Open taken',
    shootsMonth: 'Shoots deze maand', urgent: 'Urgent',
    kpiTasksInProgress: 'Taken in uitvoering',
    kpiUrgentClients: 'Urgente klanten',
    kpiDescOngoingProjects: 'Lopende trajecten',
    kpiDescScheduled: 'Gepland in agenda',
    kpiDescAcrossProjects: 'Over alle projecten',
    kpiDescRequiresAttention: 'Vereist aandacht',
    dayModalNoEvents: 'Geen events op deze dag.',
    addEventToDay: '+ Event toevoegen',
    eventFormTitle: 'Nieuw event toevoegen',
    eventNameLabel: 'Naam',
    eventNamePlaceholder: 'Event naam…',
    eventDateLabel: 'Datum',
    eventClientLabel: 'Klant',
    eventClientPlaceholder: '— Kies klant —',
    eventNotesPlaceholder: 'Optioneel…',
    thisWeek: 'Deze week', nextWeek: 'Volgende week',
    homeStudioSubtitle: 'Studio overzicht · 4REEL Productions',
    activity: 'Activiteit', contact: 'Contactpersoon',
    phone: 'Telefoon', clientSince: 'Klant sinds',
    phase: 'Fase', statusLabel: 'Status',
    urgentStatus: 'Urgent', active: 'Actief', notes: 'Notities',
    todo: 'Te doen', bezig: 'Bezig', review: 'Review', klaar: 'Klaar',
    filter: 'Filter:', allTasks: 'Alle',
    tasksKanbanSubtitle: 'Projecttaken over alle klanten',
    addTask: '+ Taak', addEvent: '+ Nieuw event',
    save: 'Opslaan', cancel: 'Annuleren', close: 'Sluiten',
    delete: 'Verwijderen', restore: '↩ Herstellen',
    archive: '→ Archiveren',
    wsFilmsLabel: 'Filmpjes', wsFilmsReady: "klaar",
    wsVidColName: 'Bestandsnaam', wsVidColFase: 'Edit Fase',
    wsVidColAssets: 'Assets Drive', wsVidColExport: 'Export Frame.io',
    wsVidColNotes: 'Notities', wsAddDrivePH: '+ Drive link toevoegen',
    wsAddExportPH: '+ Frame.io link', wsVidNamePrompt: 'Naam van het filmpje:',
    shotlistAdd: '+ Shot', reset: '↺ Reset alle vinkjes',
    shootMode: '⛶ Shoot-modus', exitShootMode: '✕ Shoot-modus',
    script: 'Script', brandAssets: 'Brand Assets', shotlist: 'Shotlist', sop: 'SOP',
    stuurNaarKlant: '→ Stuur naar klant', bijKlant: '👁 Bij klant', klantAkkoord: '✓ Klant akkoord',

    loginWrongRoleTeam: 'Dit account is geen teamaccount. Gebruik een teamaccount in Team-modus.',
    loginWrongRoleClient: 'Dit account is geen klantaccount. Gebruik een klantaccount in Klant-modus.',
    loginInvalid: 'Ongeldig e-mailadres of wachtwoord.',
    portalTitleClient: 'Klantportaal',
    portalTitleTeam: '4REEL Team',
    portalSubClient: 'Log in met je accountgegevens',
    portalSubTeam: 'Log in met je teamaccount',
    portalTabClient: '👤 Klant',
    portalTabTeam: '🔐 4REEL Team',
    portalEmailLabel: 'Emailadres',
    portalPasswordLabel: 'Wachtwoord',
    portalEmailPlaceholder: 'jouw@email.nl',
    portalLoginSubmit: 'Inloggen →',
    portalLoginSubmitLoading: 'Inloggen…',
    portalPoweredBy: 'Beveiligd portaal · 4REEL Productions',
    portalLoginTypeAria: 'Inlogtype',
    portalTeamLoggedTitle: 'Ingelogd als teamlid',
    portalTeamLoggedBody: 'Gebruik het dashboard voor teamtoegang.',
    portalTeamLoggedLink: '→ Ga naar dashboard',
    eventCreateForbidden: 'Alleen team mag events aanmaken.',
    eventValidationNameRequired: 'Vul een eventnaam in.',
    eventValidationDateRequired: 'Kies een datum.',
    eventValidationClientRequired: 'Selecteer een klant.',
    eventSaveFailed: 'Event kon niet worden opgeslagen.',
  },
  en: {
    brandSub: 'Video Production Studio',
    navStudio: 'Studio',
    navBeheer: 'Operations',
    navEditors: 'Editors',
    team: 'Team',
    logout: 'Log out',
    logoutConfirmTitle: 'Log out?',
    logoutConfirmBody: 'Are you sure you want to log out?',
    home: 'Home', agenda: 'Agenda', klanten: 'Clients', taken: 'Tasks',
    archief: 'Archive', workspace: 'Workspace', pulse: 'Studio Pulse',
    activeClients: 'Active clients', openTasks: 'Open tasks',
    shootsMonth: 'Shoots this month', urgent: 'Urgent',
    kpiTasksInProgress: 'Tasks in progress',
    kpiUrgentClients: 'Urgent clients',
    kpiDescOngoingProjects: 'Ongoing projects',
    kpiDescScheduled: 'Scheduled',
    kpiDescAcrossProjects: 'Across all projects',
    kpiDescRequiresAttention: 'Requires attention',
    dayModalNoEvents: 'No events on this day.',
    addEventToDay: '+ Add event',
    eventFormTitle: 'Add new event',
    eventNameLabel: 'Name',
    eventNamePlaceholder: 'Event name…',
    eventDateLabel: 'Date',
    eventClientLabel: 'Client',
    eventClientPlaceholder: '— Select client —',
    eventNotesPlaceholder: 'Optional…',
    thisWeek: 'This week', nextWeek: 'Next week',
    homeStudioSubtitle: 'Studio overview · 4REEL Productions',
    activity: 'Activity', contact: 'Contact person',
    phone: 'Phone', clientSince: 'Client since',
    phase: 'Phase', statusLabel: 'Status',
    urgentStatus: 'Urgent', active: 'Active', notes: 'Notes',
    todo: 'To do', bezig: 'In progress', review: 'Review', klaar: 'Done',
    filter: 'Filter:', allTasks: 'All',
    tasksKanbanSubtitle: 'Project tasks across all clients',
    addTask: '+ Task', addEvent: '+ New event',
    save: 'Save', cancel: 'Cancel', close: 'Close',
    delete: 'Delete', restore: '↩ Restore',
    archive: '→ Archive',
    wsFilmsLabel: 'Videos', wsFilmsReady: 'ready',
    wsVidColName: 'Filename', wsVidColFase: 'Edit Phase',
    wsVidColAssets: 'Assets Drive', wsVidColExport: 'Export Frame.io',
    wsVidColNotes: 'Notes', wsAddDrivePH: '+ Add Drive link',
    wsAddExportPH: '+ Frame.io link', wsVidNamePrompt: 'Video filename:',
    shotlistAdd: '+ Shot', reset: '↺ Reset all checks',
    shootMode: '⛶ Shoot mode', exitShootMode: '✕ Shoot mode',
    script: 'Script', brandAssets: 'Brand Assets', shotlist: 'Shotlist', sop: 'SOP',
    stuurNaarKlant: '→ Send to client', bijKlant: '👁 At client', klantAkkoord: '✓ Client approved',

    loginWrongRoleTeam: 'This account is not a team account. Use a team account in Team mode.',
    loginWrongRoleClient: 'This account is not a client account. Use a client account in Client mode.',
    loginInvalid: 'Invalid email or password.',
    portalTitleClient: 'Client portal',
    portalTitleTeam: '4REEL Team',
    portalSubClient: 'Sign in with your account details',
    portalSubTeam: 'Sign in with your team account',
    portalTabClient: '👤 Client',
    portalTabTeam: '🔐 4REEL Team',
    portalEmailLabel: 'Email',
    portalPasswordLabel: 'Password',
    portalEmailPlaceholder: 'you@email.com',
    portalLoginSubmit: 'Sign in →',
    portalLoginSubmitLoading: 'Signing in…',
    portalPoweredBy: 'Secure portal · 4REEL Productions',
    portalLoginTypeAria: 'Sign-in type',
    portalTeamLoggedTitle: 'Signed in as team member',
    portalTeamLoggedBody: 'Use the dashboard for team access.',
    portalTeamLoggedLink: '→ Go to dashboard',
    eventCreateForbidden: 'Only team members can create events.',
    eventValidationNameRequired: 'Enter an event name.',
    eventValidationDateRequired: 'Choose a date.',
    eventValidationClientRequired: 'Select a client.',
    eventSaveFailed: 'Could not save the event.',
  }
};

const LangContext = createContext(null);

export function LangProvider({ children }) {
  const [lang, setLang] = useState('nl');
  const t = (key) => strings[lang][key] || key;
  return (
    <LangContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LangContext.Provider>
  );
}

export const useLang = () => useContext(LangContext);
